import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateHorarioMedico1776563381354 implements MigrationInterface {
    name = 'CreateHorarioMedico1776563381354'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`imagen\` DROP FOREIGN KEY \`FK_e0de83ffb1189d65d431d3f0096\``);
        await queryRunner.query(`ALTER TABLE \`imagen\` DROP FOREIGN KEY \`FK_479a3c16c483d859845085c8487\``);
        await queryRunner.query(`ALTER TABLE \`imagen\` CHANGE \`pacienteIdPaciente\` \`pacienteIdPaciente\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`imagen\` CHANGE \`consultaIdConsulta\` \`consultaIdConsulta\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`nombre\` \`nombre\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`apellido\` \`apellido\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`dni\` \`dni\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`sexo\` \`sexo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`edad\` \`edad\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`fechaNacimiento\` \`fechaNacimiento\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`lugarNacimiento\` \`lugarNacimiento\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`direccion\` \`direccion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`telefonoFijo\` \`telefonoFijo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`telefonoCelular\` \`telefonoCelular\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`ocupacion\` \`ocupacion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`estadoCivil\` \`estadoCivil\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`obraSocial\` \`obraSocial\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`afiliadoObraSocial\` \`afiliadoObraSocial\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`antecedentesPersonalesMedicos\` \`antecedentesPersonalesMedicos\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`antecedentesQuirurgicos\` \`antecedentesQuirurgicos\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`alergias\` \`alergias\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`antecedentesHeredoFamiliares\` \`antecedentesHeredoFamiliares\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`antecedentesGinecoObstetricos\` \`antecedentesGinecoObstetricos\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`habitosToxicos\` \`habitosToxicos\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`medicacionHabitual\` \`medicacionHabitual\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoHabito\` \`examenFisicoHabito\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoPeso\` \`examenFisicoPeso\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoTalla\` \`examenFisicoTalla\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoIMC\` \`examenFisicoIMC\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoTA\` \`examenFisicoTA\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoFC\` \`examenFisicoFC\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoFR\` \`examenFisicoFR\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoTemperatura\` \`examenFisicoTemperatura\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoSistemaNervioso\` \`examenFisicoSistemaNervioso\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoAPCardiovascular\` \`examenFisicoAPCardiovascular\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoAPRespiratorio\` \`examenFisicoAPRespiratorio\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoAPDigestivo\` \`examenFisicoAPDigestivo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoAPGenitourinario\` \`examenFisicoAPGenitourinario\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoSistemaEndocrino\` \`examenFisicoSistemaEndocrino\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoSistemaHematopoyetico\` \`examenFisicoSistemaHematopoyetico\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoSistemaMusculoEsqueletico\` \`examenFisicoSistemaMusculoEsqueletico\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoPielAnexos\` \`examenFisicoPielAnexos\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`primerObservacion\` \`primerObservacion\` varchar(1000) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`laboratorios\` \`laboratorios\` varchar(1000) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`imagen\` \`imagen\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`imagen2\` \`imagen2\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`fechaCreacion\` \`fechaCreacion\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`motivoConsulta\` \`motivoConsulta\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`anamnesis\` \`anamnesis\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`examenFisico\` \`examenFisico\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`diagnostico\` \`diagnostico\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`tratamiento\` \`tratamiento\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`observaciones\` \`observaciones\` varchar(1000) NULL`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`laboratorios\` \`laboratorios\` varchar(1000) NULL`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`telefono\` \`telefono\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`colegioMedico\` \`colegioMedico\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`direccionConsultorio\` \`direccionConsultorio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`telefonoConsultorio\` \`telefonoConsultorio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`horarioAtencion\` \`horarioAtencion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`obrasSocialesAcepta\` \`obrasSocialesAcepta\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`biografia\` \`biografia\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`foto\` \`foto\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`lastLogin\` \`lastLogin\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`deleteAt\` \`deleteAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`turno\` CHANGE \`motivo\` \`motivo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`turno\` CHANGE \`notas\` \`notas\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`imagen\` ADD CONSTRAINT \`FK_e0de83ffb1189d65d431d3f0096\` FOREIGN KEY (\`pacienteIdPaciente\`) REFERENCES \`paciente\`(\`id_paciente\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`imagen\` ADD CONSTRAINT \`FK_479a3c16c483d859845085c8487\` FOREIGN KEY (\`consultaIdConsulta\`) REFERENCES \`consulta\`(\`id_consulta\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`imagen\` DROP FOREIGN KEY \`FK_479a3c16c483d859845085c8487\``);
        await queryRunner.query(`ALTER TABLE \`imagen\` DROP FOREIGN KEY \`FK_e0de83ffb1189d65d431d3f0096\``);
        await queryRunner.query(`ALTER TABLE \`turno\` CHANGE \`notas\` \`notas\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`turno\` CHANGE \`motivo\` \`motivo\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`deleteAt\` \`deleteAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`lastLogin\` \`lastLogin\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`foto\` \`foto\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`biografia\` \`biografia\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`obrasSocialesAcepta\` \`obrasSocialesAcepta\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`horarioAtencion\` \`horarioAtencion\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`telefonoConsultorio\` \`telefonoConsultorio\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`direccionConsultorio\` \`direccionConsultorio\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`colegioMedico\` \`colegioMedico\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`medico\` CHANGE \`telefono\` \`telefono\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`laboratorios\` \`laboratorios\` varchar(1000) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`observaciones\` \`observaciones\` varchar(1000) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`tratamiento\` \`tratamiento\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`diagnostico\` \`diagnostico\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`examenFisico\` \`examenFisico\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`anamnesis\` \`anamnesis\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consulta\` CHANGE \`motivoConsulta\` \`motivoConsulta\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`fechaCreacion\` \`fechaCreacion\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`imagen2\` \`imagen2\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`imagen\` \`imagen\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`laboratorios\` \`laboratorios\` varchar(1000) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`primerObservacion\` \`primerObservacion\` varchar(1000) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoPielAnexos\` \`examenFisicoPielAnexos\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoSistemaMusculoEsqueletico\` \`examenFisicoSistemaMusculoEsqueletico\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoSistemaHematopoyetico\` \`examenFisicoSistemaHematopoyetico\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoSistemaEndocrino\` \`examenFisicoSistemaEndocrino\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoAPGenitourinario\` \`examenFisicoAPGenitourinario\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoAPDigestivo\` \`examenFisicoAPDigestivo\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoAPRespiratorio\` \`examenFisicoAPRespiratorio\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoAPCardiovascular\` \`examenFisicoAPCardiovascular\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoSistemaNervioso\` \`examenFisicoSistemaNervioso\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoTemperatura\` \`examenFisicoTemperatura\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoFR\` \`examenFisicoFR\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoFC\` \`examenFisicoFC\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoTA\` \`examenFisicoTA\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoIMC\` \`examenFisicoIMC\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoTalla\` \`examenFisicoTalla\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoPeso\` \`examenFisicoPeso\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`examenFisicoHabito\` \`examenFisicoHabito\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`medicacionHabitual\` \`medicacionHabitual\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`habitosToxicos\` \`habitosToxicos\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`antecedentesGinecoObstetricos\` \`antecedentesGinecoObstetricos\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`antecedentesHeredoFamiliares\` \`antecedentesHeredoFamiliares\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`alergias\` \`alergias\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`antecedentesQuirurgicos\` \`antecedentesQuirurgicos\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`antecedentesPersonalesMedicos\` \`antecedentesPersonalesMedicos\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`afiliadoObraSocial\` \`afiliadoObraSocial\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`obraSocial\` \`obraSocial\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`estadoCivil\` \`estadoCivil\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`ocupacion\` \`ocupacion\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`telefonoCelular\` \`telefonoCelular\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`telefonoFijo\` \`telefonoFijo\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`direccion\` \`direccion\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`lugarNacimiento\` \`lugarNacimiento\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`fechaNacimiento\` \`fechaNacimiento\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`edad\` \`edad\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`sexo\` \`sexo\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`dni\` \`dni\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`apellido\` \`apellido\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`paciente\` CHANGE \`nombre\` \`nombre\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`imagen\` CHANGE \`consultaIdConsulta\` \`consultaIdConsulta\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`imagen\` CHANGE \`pacienteIdPaciente\` \`pacienteIdPaciente\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`imagen\` ADD CONSTRAINT \`FK_479a3c16c483d859845085c8487\` FOREIGN KEY (\`consultaIdConsulta\`) REFERENCES \`consulta\`(\`id_consulta\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`imagen\` ADD CONSTRAINT \`FK_e0de83ffb1189d65d431d3f0096\` FOREIGN KEY (\`pacienteIdPaciente\`) REFERENCES \`paciente\`(\`id_paciente\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
